{
    "h-0": "Home",
    "f-1": "Home/Favorites/Validation List",
    "f-2": "Home/Favorites/Rejection List",
    "f-3": "Home/Favorites/Collection List",
    "f-4": "Home/Favorites/New Case",
    "c-1": "Home/Claims/Validation List",
    "c-2": "Home/Claims/Rejection List",
    "c-3": "Home/Claims/Collection List",
    "c-4": "Home/Claims/New Case",
    "d-1": "Home/dashboard/Validation List",
    "d-2": "Home/dashboard/Rejection List",
    "d-3": "Home/dashboard/Collection List",
    "d-4": "Home/dashboard/New Case",
    "em-1": "Home/Letter Center",
    "em-11": "Home/Letter Center/Generate",
    "em-12": "Home/Letter Center/Print Center",
    "em-13": "Home/Letter Center/Letter Presents",
    "em-2": "Home/Invalid Letter Mapping",
    "em-21": "Home/Invalid Letter Mapping/Lorem ipsum dolor sit",
    "m-1": "Home/Members/Validation List",
    "m-2": "Home/Members/Rejection List",
    "m-3": "Home/Members/Collection List",
    "m-4": "Home/Members/New Case",
    "p-1": "Home/Payment Center/Validation List",
    "p-2": "Home/Payment Center/Rejection List",
    "p-3": "Home/Payment Center/Collection List",
    "p-4": "Home/Payment Center/New Case",
    "op-1": "Home/Auditor Files",
    "op-11": "Home/Auditor Files/Files History",
    "op-12": "Home/Auditor Files/Upload Claim File",
    "op-2": "Home/Notifications",
    "op-21": "Home/Notifications/Alerts",
    "op-22": "Home/Notifications/Phone Logs",
    "op-3": "Home/Algorithm Management",
    "op-31": "Home/Algorithm Management/Configurations",
    "op-32": "Home/Algorithm Management/Listing",
    "op-33": "Home/Algorithm Management/Adjustment Reason List",
    "op-34": "Home/Algorithm Management/Rejection Reason List",
    "op-35": "Home/Algorithm Management/Statutory Limit Settings",
    "op-4": "Home/Task Assignment",
    "op-41": "Home/Task Assignment/New Task",
    "op-42": "Home/Task Assignment/Re-Assign Task",
    "op-43": "Home/Task Assignment/My Team Tasks",
    "op-44": "Home/Bulk Update/My Tasks"
}